### ISSUE TITLE
Question에 답변달면 에러

### ISSUE THREAD

**Issue by koyrkr** [swsnu/swpp2020-team8#114]
Question에 답변달면 에러 
(onResetContent is not a function 에러! 근데 다시 로긴하면 글에 추가가 되어있긴 함)
![image](https://user-images.githubusercontent.com/42240753/100523284-b0069480-31f2-11eb-8e30-a815794e0556.png)

**Comment by curious-curie** [comment]
제 브랜치에서 고쳤습니다~ 머지 후 확인 부탁
