### ISSUE TITLE
Post 공개 범위가 비어있는 경우가 있음

### ISSUE THREAD

**Issue by koyrkr** [swsnu/swpp2020-team8#116]
공개 범위가 비어있는 경우가 있음

**Comment by ssm0318** [comment]
사진 캡처 + 어떤 페이지에서 그랬는지 + 당시 json response는 뭐였는지 이런 것도 같이 적어주면 도움이 될 것 같슴다...! @koyrkr

**Comment by ssm0318** [comment]
아 이거 본인 글이 아닐 때에도 '공개범위:'라는 글씨를 지우지 않아서 그런 것 같네요 @GooJinSun 확인 부탁드려요~

**Comment by ssm0318** [comment]
익명피드에서도!
