### ISSUE TITLE
Comment 자기의 글에 비밀댓글을 달았을때 다른 친구인 유저가 볼 수 있나?

### ISSUE THREAD

**Issue by koyrkr** [swsnu/swpp2020-team8#119]
자기의 글에 비밀댓글을 달았을때 다른 친구인 유저가 볼 수 있나? (지금은 볼 수 있게 되어있음)

**Comment by curious-curie** [comment]
지금 안오는 것 같은데 상황 자세하게 다시 써줄 수 있어? 
![image](https://user-images.githubusercontent.com/47528556/100585546-1c87ad80-3331-11eb-962f-99df08d546aa.png)
(adoor로 로그인)

![image](https://user-images.githubusercontent.com/47528556/100585563-23162500-3331-11eb-9792-97861bc9f6f7.png)
(curie로 로그인)

**Comment by koyrkr** [comment]
이 부분은 나도 다시 확인해봤는데 문제 없는 것 같아 ㅠㅠ 혼란스럽게 해서 미안...!
