### ISSUE TITLE
Comment 자기 글에 달린 댓글은 다 지울수있게 해야하지 않나? (author가)

### ISSUE THREAD

**Issue by koyrkr** [swsnu/swpp2020-team8#120]
자기 글에 달린 댓글은 다 지울수있게 해야하지 않나? (author가)

**Comment by curious-curie** [comment]
삭제 permission 은 author only로 알고있는데 아닌강?

**Comment by koyrkr** [comment]
아하! 근데 사실 정하기나름인것같다! 그럼 버그는아니지만, 어떻게 하면 좋을지 미팅때 다시 얘기해봅시다!

**Comment by ssm0318** [comment]
@curious-curie 맞아요
@koyrkr 필수적이거나 필요한건지는 잘 모르겟습니다..!

**Comment by koyrkr** [comment]
@curious-curie @ssm0318 아하 그럼 그냥 author only도 합시다! 좋아요~~
