### ISSUE TITLE
friend 아무도 없는 사람의 피드에 아무글 보여주기 

### ISSUE THREAD

**Issue by curious-curie** [swsnu/swpp2020-team8#124]
현재 회원가입 후 친구 아무도 없는 회원이 홈 피드로 리다이렉트 되면 아무런 result도 없다

백엔드에서 이거 수정하거나,
너무 공수가 많이 들것 같으면 회원가입 후엔 anonymous feed로 리다이렉트 시키는 것도 괜찮을 듯

**Comment by ssm0318** [comment]
이건 우리가 광고 컨텐츠를 붙이지 않는한 당ㅇ연한 것 같은데 친구를 추가해보세요 / 질문에 답해보세요 같은 안내문을 적어주는게 자연스러울 것 같습니다
