### ISSUE TITLE
[Sprint 3] Backend 과제

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#13]
심심할 여러분을 위해 새로운 과제를 가져와봤어요~! ^0^

과제 간단 소개: backend 모델을 구현한 두 가지 방법을 다 이해하고 리팩터링한 버전에 맞게 api/action 등을 수정함으로써 우리 플젝에 필요한 모델 관련 내용을 완벽 마스터했음을 증명한다~!

## TODO 
1. [feature/backend-models-refactor 브랜치](https://github.com/swsnu/swpp2020-team8/tree/feature/backend-models-refactor)와
[feature/backend-models 브랜치](https://github.com/swsnu/swpp2020-team8/tree/feature/backend-models) 브랜치 각각에 모델이 구현되어 있습니다.
두 가지 구현 방법의 차이점 혹은 장/단점이 무엇인지 최소 3가지 이상 양심을 가지고 찾아보세요. ('모델 이름이 다르다' 같은 시시한 건 당근 안 됨~)
모르는 부분이 발견되면 브랜치 각각 풀리퀘 날려놓을테니까 코멘트로 달아서 물어봐주시면 될 것 같습니다~~
꼭 제가 아니더라도 답하실 수 있는 분들은 언제든지 나서서 답변을 남겨주세요!

2. Documentation 수정
design & planning document를 바뀐 모델 디자인 (feature/backend-models-refactor 브랜치 기준!!)에 따라 수정해주세요!! 귀찮더라도 미리 수정해둬야 나중에 개발할 때 편할거에요~~~
각자 
진선 - ER Diagram
지나 - API
규리 - axios design
을 담당해서 수정해주시면 됩니다!!
모델을 잘 익혔다면 이 부분 수정하는건 어렵지 않을거에요!

### DUE: 2020/11/10 (Tue) **미팅 전까지**
* 진선
- [x] ER Diagram
* 지나
- [x] API
* 규리
- [ ] axios design

불만 있으면 말로해~
화!이!텡!!!!!!!!

**Comment by curious-curie** [comment]
말로안하고발로해도되나요?

**Comment by ssm0318** [comment]
그건 안 됩니다.
눈빛까지는 허용해드릴 수 있습니다.

**Comment by ssm0318** [comment]
@curious-curie 브랜치 둘 다 수정해뒀어요~

**Comment by GooJinSun** [comment]
### `feature/backend-models` 브랜치와 `feature/backend-models-refactor` 브랜치의 차이점
- **Adoor Model**
  - 모델들 전반에 걸쳐 존재하는 필드, `created_at`, `updated_at`, `content`를 [Abstract base classes](https://docs.djangoproject.com/en/3.1/topics/db/models/#abstract-base-classes)를 활용해 리팩토링 함

    > Abstract base classes are useful when you want to put some common information into a number of other models. You write your base class and put abstract=True in the Meta class. This model will then not be used to create any database table. Instead, when it is used as a base class for other models, its fields will be added to those of the child class.

    ```python
    class Meta:
            abstract = True
    ```
    - ~~`created_at`으로 정렬할 필요는 없을까? [ordering](https://docs.djangoproject.com/en/3.1/ref/models/options/#ordering) => `Post Model`에 있었음~~

- **`Polymorphic Model` vs `AdoorModel`, `GenericForeignKey`**
  - `Feed`를 polymorphic model로 구현했던 것을, `Article`, `Response`, `Question`, `Post` 모두 `AdoorModel`을 base로 해서`AdoorModel`의 세 가지 필드를 자동으로 갖게 함
  - `Post`와 `Article`, `Response`, `Question`의 관계는 `Post`의 `GenericForeignKey`로
    - `Response`모델의 `GenericForeignKey`는 무슨 용도인지 궁금합니다!

- **`Question`, `AdminQuestion`, `CustomQuestion` vs `QuestionManager`**
  - admin/custom question은 질문의 작성자만 빼고 필드가 같으므로, `Question`모델로 합치고, `is_admin_question`필드를 추가하고, `QuestionManager`라는 default manager를 둠
    - 따라서`Question` query를 날릴 때 둘을 구분하려면 다음과 같이 하면 될 듯..? ~~맞나요?~~~
    ```python
    // custom question
    Question.objects.admin_questions_only()
    // admin question
    Question.objects.custom_questions_only()
    ```
  - `Like`, `Comment`에도 적용

- 새로 알게 된 것
  - `ForeignKey` vs [`GenericForeignKey`](https://docs.djangoproject.com/en/dev/ref/contrib/contenttypes/#generic-relations)
      - `ForeignKey`는 하나의 모델과만 관계를 가질 수 있지만, `GenericForeignKey`는 여러 모델과 관계를 가질 수 있음
      > A normal ForeignKey can only “point to” one other model, ... The contenttypes application provides a special field type (GenericForeignKey) which works around this and allows the relationship to be with any model
      - `filter()`, `exclude()` method를 사용하지 못함
       ```python
        # This will fail
        TaggedItem.objects.filter(content_object=guido)
        # This will also fail
        TaggedItem.objects.get(content_object=guido)
      ```
    - [`GenericRelation`](https://docs.djangoproject.com/en/dev/ref/contrib/contenttypes/#django.contrib.contenttypes.fields.GenericRelation): reverse generic relation

- [ER diagram](https://lucid.app/lucidchart/f5d93802-3da4-4436-85fe-7f0b8a13a35b/edit?shared=true&page=DeaHeU2MB_vi#?folder_id=home&browser=icon)

**Comment by ssm0318** [comment]
@GooJinSun 아주 잘했어요~~~ 훌륭하네요~~~ 
refactor한 버전에서 target이 필요없는 것! 맞습니다~~ 아주 꼼꼼하게 잘 보셨네요!!!
반영해서 수정했습니다~~~ ^0^

**Comment by koyrkr** [comment]
[backend homework.docx](https://github.com/swsnu/swpp2020-team8/files/5516007/backend.homework.docx)

저두 백엔드 숙제한거 올려봅니다...! (부끄)

**Comment by curious-curie** [comment]
* Abstract Model (Adoor Model)을 선언하여 게시하는 종류의 모델들 (Post, Comment)들을 구현할 때 extend하여 구현 

* Models.Manager 사용하여 쿼리 작업
    * Filtering하는 method 등… 
    * e.g. Comment.objects.replies_only()

* Signal 사용

-   특정 액션이 발생하면 그 후에 발생하는 이벤트 (django를 포함한 여러 프레임워크에 존재)
-  저장하기 전/후, 삭제하기 전/후 등 특정 signal이 웹 어플리케이션에 전달 e.g. 회원가입 후 ‘축하합니다’ 메일 보낼 때 signal
        
*  Signal 종류
            * pre_save : 저장 전, 실행
            * post_save : 저장 후, 실행
            * pre_delete : 삭제 전, 실행
            * post_delete : 삭제 후, 실행

근데 create_post 등 Feed/Models.py의 함수에서 signal이 왜 필요한건지 모르게쒀,,
views.py 안에서 ViewSet extend한 함수에서 create 함수를 정의해서 하는 식으루?? 해도 되는거 아닐까? 
사실 제가 잘 이해를 못한 것 같아요... 

```class RegistrationAPI(generics.GenericAPIView):
    serializer_class = CreateUserSerializer

    def post(self, request, *args, **kwargs):
        if len(request.data["username"]) < 6 or len(request.data["password"]) < 4:
            body = {"message": "short field"}
            return Response(body, status=status.HTTP_400_BAD_REQUEST)
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        return Response(
            {
                "user": UserSerializer(
                    user, context=self.get_serializer_context()
                ).data,
                "token": AuthToken.objects.create(user)[1],
            }
        )
``` 

혹은 이런식으로, views 내에서 API 를 상속받아서 하는 방식??만 알고 있었어서 그런 것 같아요

```
class PlaylistViewSet(viewsets.ModelViewSet):
    queryset = Playlist.objects.all()
    serializer_class = PlaylistSerializer
    
    def get_queryset(self):
        return Playlist.objects.all().order_by("-created_at")

    def perform_create(self, serializer):
        post = Post.objects.get(id=self.request.data['track'])
        serializer.save(owner = self.request.user, track=post)

```


* 그리구 Create_post 부분에 if else 해서 하는 것 있잖아요 그부분 `get_or_create` 함수 쓰면 될 듯!!!
