### ISSUE TITLE
[Like] 자기 글을 좋아요 누르면 노티에 알림이 온다?!

### ISSUE THREAD

**Issue by koyrkr** [swsnu/swpp2020-team8#136]
내 게시글 좋아요 누르면 '{나}님이 회원님의 게시글을 좋아합니다'
이대로 괜찮을까요?! 아니면은 자기가 누른건 like 노티가 안와야할까요? 

![image](https://user-images.githubusercontent.com/42240753/100626713-80c66380-3369-11eb-9eb2-3e805757d6cd.png)

**Comment by ssm0318** [comment]
댓글의 경우도 마찬가지
