### ISSUE TITLE
question detail page 의 ui

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#154]
![스크린샷 2020-12-03 오후 7 58 55](https://user-images.githubusercontent.com/25769209/101001944-1ef13e00-35a3-11eb-9263-02e1134fcd56.png)
1. 답변이 없을 때 그냥 표시할 게시물이 없다고 하는 것보다는 답변 div를 만들고 헤더를 준 후 비워두거나 '아직 작성된 답변이 없습니다'라고 해주는게 어떨까요?
2. 답변 작성란이 2-3줄은 되면 좋을 것 같아요

**Comment by GooJinSun** [comment]
'답변' 이라는 헤더를 추가
