### ISSUE TITLE
question detail page 익명의 답변보기 toggle button

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#155]
![스크린샷 2020-12-03 오후 7 59 40](https://user-images.githubusercontent.com/25769209/101002582-64157000-35a3-11eb-8a03-60253b6aa99f.png)
'익명의 답변보기'라는 버튼이 무슨 뜻인지 잘 모르겠어요
전체 | 친구만 | 익명만 이렇게 세 옵션이 있는건줄 알았는데
전체 보기 vs 익명 답변만 보기 이렇게 두 개 옵션인건가요?
익명답변만 보고 싶을때는 언제일까요?

**Comment by ssm0318** [comment]
익명의 답변'만'보기 vs 익명의 답변'도' 보기 중에 어떤 것일까유

**Comment by GooJinSun** [comment]
전체 | 친구만 | 익명
이렇게 바꿀까하는데 어떤가요? @ssm0318

**Comment by ssm0318** [comment]
@GooJinSun 조효ㅡㅂ이당
