### ISSUE TITLE
user profile의 ME 버튼

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#158]
![스크린샷 2020-12-03 오후 8 01 02](https://user-images.githubusercontent.com/25769209/101006986-a7241300-35a4-11eb-9379-934580b50bc7.png)
ME 버튼은 무엇인가요...?
눌러도 아무것도 안 되는데?

**Comment by koyrkr** [comment]
그때 얘기했던 my-page인지 알 수 있게 하는 요소로 추가한 것 같아! mobile-ui하면서 @curious-curie 가 추가한 것으로 알고 있슴다!

**Comment by ssm0318** [comment]
@koyrkr @curious-curie ㅋㅋㅋㅋ조금 이상한 것 같은데 그냥 없애는건 어떨까요? 
내가 아니면 친구 요청/친구 관계 버튼이 있고, 나면 버튼이 없고
우리가 지금 프사가 애매해서 구분이 안되는데 프사가 생기면 사실 나 vs 다른 사람 구분이 힘들진 않을듯..!
(그걸 따로 저렇게 구분해주는 서비스가 있나..?)
