### ISSUE TITLE
header icon 배치

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#161]
![스크린샷 2020-12-03 오후 8 18 43](https://user-images.githubusercontent.com/25769209/101010418-a50e8400-35a5-11eb-8355-f27da71ad75b.png)
noti랑 current user profile 버튼 간의 간격이 좀 흐트러진 것 같아요!
그리고 hover시 뒤에 보이는 그림자가 원이 아니고 타원형인건 왜때문일까요?

**Comment by koyrkr** [comment]
요거 제가 한번 쪼끔 손봐볼게요!

**Comment by koyrkr** [comment]
![image](https://user-images.githubusercontent.com/42240753/101052488-021c3100-35ca-11eb-8d6e-f5c47978c7ec.png)

간격은 요 정도로 조정했는데 어떤가요?!

**Comment by ssm0318** [comment]
베리굿~
