### ISSUE TITLE
[Notifications] adoor가 아닌 유저에 대해 노티를 가져오지 못하는 버그

### ISSUE THREAD

**Issue by GooJinSun** [swsnu/swpp2020-team8#175]
**Describe the bug**
- adoor가 아닌 유저에 대해 노티를 가져오지 못하는 문제`/api/notifications/` (admin계정은 이상하게 잘됨)
  - 관련 백엔드 수정 필요
  - 노티 가져오는 request실패 시에 frontend에서 request를 계속해서 보내는 문제 수정 필요
[related sentry error link](https://sentry.io/organizations/adoor/issues/2073584251/?project=5543025&query=is%3Aunresolved&statsPeriod=14d)

**To Reproduce**
1. 어드민이 아닌 계정으로 로그인한다
2. /home이 아닌 다른 페이지로 접속
3. url전환에 따라  `GET /api/notifications'
4. 노티를 가져오지 못함
5. /login으로 리다이렉트를 반복하며 `GET /api/notifications`를 무한 호출

**Expected behavior**
- backend Error수정
- 프론트에서 무한루프 수정

**Screenshots**
![image](https://user-images.githubusercontent.com/37523788/101288329-5842db80-3839-11eb-8542-cf8df2dca6b3.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome, safari

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS
 - Browser safari, chrome

**Additional context**
- 프론트 관련 버그는 제가 수정하겠습니다!
- @ssm0318 이거 봐줄 수 있나요??

**Comment by ssm0318** [comment]
어드민이 아닌 계정이라 그런건 아니고 friend request 등 노티를 cascade해서 삭제하는걸 방지하는 코드를 달고나서 생기는 exception이 따로 잡히지 않아서 생기는 문제였는데 고쳐놓은 것 같고 hot-fix 브랜치에 푸시했어용

**Comment by GooJinSun** [comment]
[AttributeError /api/notifications/](https://sentry.io/organizations/adoor/issues/2076349824/?project=5543025&query=is%3Aunresolved)
![image](https://user-images.githubusercontent.com/37523788/101322794-f458fb00-38aa-11eb-9386-253f0fd69647.png)
hotfix머지했는데 안고쳐진것 같아요!!
디플로이 해둔 것에서 http://ec2-54-237-96-51.compute-1.amazonaws.com/
sunny__9__ / sunny
로 로그인하면 에러 확인할 수 있는데, 다시 확인 부탁드립니당 @ssm0318

**Comment by ssm0318** [comment]
이게 jinsun goo 계정에서도 그렇지는 않죠?

**Comment by ssm0318** [comment]
@GooJinSun

**Comment by ssm0318** [comment]
이전 문제는 고쳐졌었고
이번 문제는 어드민 계정을 세 명의 개인 계정을 만든 후에 만들어서
반갑습니다 노티에 actor가 admin이어야 하는데 비어있게 되어 생긴 문제입니다
앞으로 생길 노티에서는 그럴 일이 없고
이전 노티들의 actor는 서버 쉘에서 변경해뒀으니까 아마 괜찮을거에요

**Comment by GooJinSun** [comment]
우웅 맞아요!!

**Comment by ssm0318** [comment]
는 또 다른 종류의 문제가 있어서 그건 수정할게요 
Delete cascade 안 되게 한게 파장이 크군..ㅜ

**Comment by ssm0318** [comment]
그 다른 문제도 해결한 것 같습니다 서버에서 바로 해뒀고 마스터에도 반영할게요
