### ISSUE TITLE
[question] 모바일에서는 질문 모음 페이지에서도 새로운 질문 버튼 놓기 ?? 

### ISSUE THREAD

**Issue by curious-curie** [swsnu/swpp2020-team8#176]
새로운 질문 만들 수 있는 버튼의 접근성이 모바일 에선 조금 떨어지는 것 같음
질문 모음 페이지에서도 위에 새 질문 만들 수 있는 버튼을 두는게 어떨까요??

**Comment by koyrkr** [comment]
굳~~~ 좋은 생각입니다
