### ISSUE TITLE
Comment UI + timestamp

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#181]
댓글에는 timestamp가 없는데
Timstamp와 함께 댓글을 두 줄로 만들어서 좀 더 안정적으로 만들어주면 어떨까요?
![Screenshot_20201207-113626_Chrome.jpg](https://user-images.githubusercontent.com/25769209/101303062-92839b80-3880-11eb-8d3f-b6a210b7179e.jpg)
![20201207_113648.jpg](https://user-images.githubusercontent.com/25769209/101303066-957e8c00-3880-11eb-9360-15faf688fa27.jpg)

**Comment by ssm0318** [comment]
![Screenshot_20201210-064242_Chrome.jpg](https://user-images.githubusercontent.com/25769209/101692096-04dbc200-3ab3-11eb-9183-cee54def30dd.jpg)
그리구 삭제 버튼이 아이콘이어서 손가락이 뾰족해야듀ㅣ는데 글씨면 두 글자라 좀 더 누르기 편할 것 닽아요

**Comment by GooJinSun** [comment]
@ssm0318 수정되었습니다!!
