### ISSUE TITLE
[Notification Dropdown List] 노티 드롭다운리스트를 열고 로그아웃하면 fold가 안된다.

### ISSUE THREAD

**Issue by koyrkr** [swsnu/swpp2020-team8#183]
![image](https://user-images.githubusercontent.com/42240753/101306108-67507a80-3887-11eb-9abd-50ac9a8fe2a4.png)

노티 드롭다운리스트를 열고 로그아웃을 하면 이런 상황이 발생!

**Comment by ssm0318** [comment]
이거 제가 전에 close when clicked outside를 search dropdownlist랑 같이 적용시켜놨었는데
그거 복구시키면 될 것 같아요 그게 왜 사라졌지?

**Comment by koyrkr** [comment]
@ssm0318 으음 아직 같이 있는 것 같은데 아마 get noti가 제대로 작동하지 않아서 그런거같기도 하고?! 일단 noti 쪽 고쳐지면 다시 제가 나중에 기억하고 체크해볼게요!

**Comment by ssm0318** [comment]
@koyrkr 저 드랍다운이 열린다는건 get noti가 잘 된다는거 아니야?

**Comment by koyrkr** [comment]
![image](https://user-images.githubusercontent.com/42240753/101316262-8529d980-389f-11eb-8c8a-7b58642ead21.png)

@ssm0318 으음 그냥 홈에서 새로고침만 해도 이렇게 뜨는데.. 좀 더 원인분석을 해볼게!

**Comment by ssm0318** [comment]
@koyrkr hot fix 풀 해도 그런거지?

**Comment by koyrkr** [comment]
@ssm0318 응응 그러하네 ㅠㅠ

**Comment by ssm0318** [comment]
음 근데 저건 로컬호스트가 아닌 것 같은데? 서버에서 핫픽스 받고서 서버 껐다 켰어? 로컬호스트에서도 저래?

**Comment by koyrkr** [comment]
@ssm0318 맞아맞아 내가 풀받아놓고 계속 디플로이 사이트에서 시도했었다...ㅎ

로컬 호스트에서 핫픽스 받고 서버 껐다 켜서 하면 저 에러는 사라지고 노티 아이템도 잘 가져와!!!

![image](https://user-images.githubusercontent.com/42240753/101319163-d6889780-38a4-11eb-9287-16e9422b9715.png)

여전히 onclickoutside? 이건 안되는 것 같아 ㅠㅠ

![image](https://user-images.githubusercontent.com/42240753/101322615-ad6b0580-38aa-11eb-9afe-445ce9fc407e.png)

저기서 notiIconRef만 onClickoutside를 먹이면 아웃사이드 클릭이 잘 되는데, 저렇게 notiRef랑 같이 두면 잘 안되는듯?! 방법을 찾아보겠으!
