### ISSUE TITLE
post delete 시 500 error

### ISSUE THREAD

**Issue by curious-curie** [swsnu/swpp2020-team8#186]
![image](https://user-images.githubusercontent.com/47528556/101330131-9c73c180-38b5-11eb-8e1d-e7c6937f0a10.png)

```
Request URL: http://ec2-54-237-96-51.compute-1.amazonaws.com/api/feed/responses/4379/
Request Method: DELETE
Status Code: 500 Internal Server Error
```

**Comment by ssm0318** [comment]
@curious-curie 이거 혹시 어드민 페이지에서 삭제하려고 한건가?

**Comment by curious-curie** [comment]
@ssm0318  아뉘!! 그냥 로그인하구 사이트 안에서!
