### ISSUE TITLE
사용자가 생성하지 않은 데이터가 생성됩니다

### ISSUE THREAD

**Issue by GooJinSun** [swsnu/swpp2020-team8#188]
**Describe the bug**
사용자가 생성하지 않은 데이터가 생성됩니다

**To Reproduce**
`set_question_seed()`이외에 seed를 한적이 없는데
계속해서 무작위 데이터가 생성됩니다

**Expected behavior**
사용자가 생성한 데이터가 아니라면 생성되면 안됩니다ㅠㅠ

**Screenshots**
![image](https://user-images.githubusercontent.com/37523788/101330414-ea88c500-38b5-11eb-9933-8143c1438f9a.png)

**Additional context**
혹시 이유를 아시는 분?ㅠㅠ

**Comment by ssm0318** [comment]
ml feature 때문에 지금 임시 데이터 만들고 있는 중인데 곧 노티 삭제할게요!
