### ISSUE TITLE
익명댓글 추가 

### ISSUE THREAD

**Issue by GooJinSun** [swsnu/swpp2020-team8#200]
- New Comment
  - 내 게시물일 경우: 친구/익명댓글 모두 보여짐
  - 피드에 따라: 홈 -> 댓글 작성시 친구에게만 공개된다는 알림 문구, 익명 -> 댓글작성시 익명에게만 공개된다는 알림문구
  - 디테일 => (노티의 종류에 따라) 마찬가지
  - 마이페이지 => 친구에게만 공개되는 댓글만 있음

**Comment by curious-curie** [comment]
@ssm0318 댓글달 때 백엔드에 추가로 보내야 하는 필드 생기면 알려주시면 감사하겠습니다~
