### ISSUE TITLE
question feed에서 답변 작성 시

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#211]
question feed에서 답변 작성하고 나니 답변은 안 보여서 뭔가 알림을 줄 수 있으면 좋지 않을까 하는 생각이 드네요
question detail 갈 생각을 유저는 못할테니!
답변 작성란 밑에 '질문을 클릭하시면 작성된 답변들을 모두 확인하실 수 있습니다'라고 써주기...?
우리 너무 설명이 많은 서비스인가 싶기도 하고...ㅋㅋㅋㅋㅋㅋ 온갖 form마다 다 설명설명

**Comment by curious-curie** [comment]
question feed에서 답변 작성했으면 question detail 페이지로 리다이렉트 시키는건 우때여? 페이지 이동이라서 좀 유저 입장에서 느리긴 할텐데 그래도 자기 답변이 보이는게 좋을 것 같은데 제생각엔!

**Comment by ssm0318** [comment]
@curious-curie 좋은 것 같아유!
