### ISSUE TITLE
selected question 페이지를 벗어날 때 리셋되면 좋을 것 같아요 

### ISSUE THREAD

**Issue by curious-curie** [swsnu/swpp2020-team8#217]
현재 selected question이 페이지 벗어나도 계속 유지되는데
그러다보니 question id 1 detail page 방문 => 피드 복귀 => 2 detail page 방문 
하면 2페이지에서 question id 2를 불러오는 동안 question 1 이 화면에 보여요 
그래서 question detail page unmount 때 리셋하는게 좋을것같아ㅛㅇ

**Comment by GooJinSun** [comment]
@curious-curie 이거 규리가 보고잇는중이양??
