### ISSUE TITLE
노티 페이지 관련 프론트 버스

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#243]
![Screenshot_20201210-063448_Chrome.jpg](https://user-images.githubusercontent.com/25769209/101691345-eb864600-3ab1-11eb-91f6-5a4c37be5abd.jpg)
노티가 반복되는 버그

![Screenshot_20201210-063501_Chrome.jpg](https://user-images.githubusercontent.com/25769209/101691365-f04afa00-3@ab1-11eb-8869-fb446ba92163.jpg)
질문을 누르면 매번 저게 순간저긍로 보인 후 detail 페이지로 가진다는 것

**Comment by curious-curie** [comment]
Bus

**Comment by curious-curie** [comment]
나는매일학교가는버스안에서~

**Comment by ssm0318** [comment]
ㅁㅊㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ머냐고...ㅋㅋㅋㅋㅋㅋㅋㅋㅋ
