### ISSUE TITLE
friend widget이 짤려요(?)

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#264]
친구 수가 늘어나니까 friend widget이 화면 밖으로 나가는데 위젯이 고정되어 있어서 스크롤을 해도 친구가 보이지 않아요 (저 밑에 두 명이 더 있어야 합니다!)
위젯 접는걸 가능하게 해도 스크롤은 안 되겠죠 펼쳤을때...? 전체보기 버튼을 만들고 페이지를 따로 만들어야 하려나?
<img width="1439" alt="스크린샷 2020-12-11 오후 4 15 11" src="https://user-images.githubusercontent.com/25769209/101874325-0d73eb80-3bcc-11eb-8f04-d5e941df1f84.png">

**Comment by curious-curie** [comment]
최대 길이 고정하고 스크롤 되게 했어요 (question send modal도)

**Comment by ssm0318** [comment]
@curious-curie 나이서ㅓㅓ 감사합니다!!
