### ISSUE TITLE
[Sprint 4] Hello Sprint 4 

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#45]
안뇽 여러분 나이스투미츄 이제 본격 독재정권 시작이야 기대해 ʕ•ﻌ•ʔ ♡

지난 번 회의 때 이야기한거지만 우리의 신체 및 정신 건강과 생명연장을 위해 이번 스프린트에서 지켜야할 것들을 리마인드 해봅시다 -
1. **데일리 개발 coverage report 적기**
- to-do에 대한 coverage test를 매일 돌릴거에요. 
- 본인이 다음 날까지 할 일의 몇 %의 어떤 일들 cover하고자 하는지 매일 밤 미리 적어두기
- 어떤 것들을 구현해냈고, 구현한 결과 몇%의 coverage를 달성한 것 같은지 기록
- 계획만큼 달성하지 못했을 경우 이유 적어두기 (나중에 technical issues 관련 sprint report 쓰기 편해짐~)
- progress는 절대 지방방송 스타일 no~ 각자가 뭘 하고 있는지 명확히 알고 있기
(예시는 아래 댓글로 적어둘게요)

2. **<지나와 함께하는 왁자지껄 코딩 타임> 참석하기**
- [스케줄](https://docs.google.com/spreadsheets/d/1cWjYtUULBCNp54im-eKqfy9vNsbJnzJNjBC8VJnxUKg/edit?usp=sharing)
- 지나는 전날 리마인드 주기, 이멀전시 아니면 캔슬 ㄴㄴ, 캔슬 시 미리 말하기

3. **효율적으로 + 명확하게 소통하기**
- 남이 구현한 것에 대한 질문은 남한테 빠르게 물어보기 (단, 본인의 이해를 위해서라도 핑프 컨셉보다는 성의있는 질문이 좋음 e.g. 모르는 코드 발견될 때마다 바로 물어보기 x, 모르는거 찾아본 후 이거 맞아~? 하고 yes/no 질문 물어보기 o 그렇다고 이해 안 되는데 계속 붙잡고 있기 x)
- 단순한 질문만 슬랙으로
- 단순하지 않은 질문은 최대한 답변자가 있는 곳으로 찾아가서 묻기 (네 명 모두 최대한 사당에 자주 모이기)
- 버그 레포트는 본인의 실수가 아닌지, 진짜 버그가 맞는지 꼼꼼히 확인한 후 이슈에 남기기
- dependency 문제가 발생할 경우 해당 문제 피해갈 수 있는 방법 잘 의논해서 개발하기

4. **냄새 안 나는 코딩하기**
- 모르는 부분 코드 작성할 시 단순히 검색 결과 첫번째로 나오는 코드 쬑금 바꿔서 복붙해놓지 않기 --> 해당 코드에 대해 남들이 물어봤을 때 본인이 명확히 답할 수 있을 만큼 제대로 이해하기 + 우리 코딩 스타일에 맞게 짜기
- feature 구현할 때마다 testing도 바로 하기! testing 몰아서 하기 절대 no~ 테스팅 꼼꼼하게!

5. **팀원 챙기기**
- 물어보지 않아도 도움 주기 + 미안해하지 않기
- 본인이 맡은 것만 하면 끝이라는 컨셉 x, to-do는 최종 책임자를 적어둔 것일 뿐이라는 마음가짐으로 다른 사람이 맡은 것도 돕기
- 서로 to do coverage report 자주 방문해서 구경하고 잘했다고 칭찬 댓글 적어주기
- 배고프다고 자주 말하는 팀원에게 아몬드브리즈 사주기 (중요)

**Comment by ssm0318** [comment]
(예시)
<김짱구 Daily To-do Coverage Report>
(아래 to-do list는 to-do issue에서 복붙해와도 좋고 본인이 원하는대로 좀 더 세분화해서 적어도 좋습니당)

_Last Updated:_ 2020/11/25

[Frontend]
- [ ] Login Page
- [ ] Login Edit/Delete API Linking
- [ ] Logout Page
- [ ] Logout Edit/Delete API Linking

[Backend]
- [ ] Story model + serializer (including JSON validation) + view
- [ ] API testing for implemented views
- [X] sign up testing
- [ ] sign in testing
- [X] logout testing
- [ ] hello world

| 어제 상태 | 어제 계획 | 현재 상태  | 내일 계획 |
|-|-|-|-|
| 25% | 40% | 30% | 45% |
|  | sign up testing, sign in testing 구현 | sign in testing 미완성 | Login Page, hello world 구현 |

<작업 중인 브랜치>
- feature/backend-lalala (PR)
- feature/backend-hahaha (in progress)

<어려웠던 점> (sprint report 때 활용 가능하니 전날 기록 지우지 말고 cumulative하게 적읍시다)
1.  django rest framework 알아보다보니 시간이 다 감
2.  sign in이 지지리도 안 됨 F-RFVF token이 X에러를 내서 Y페이지에서 처리하고자 했으나 Z가 되어 떠남

**Comment by ssm0318** [comment]
위 템플릿 때문에 기록이 번거로워지면 템플릿을 변경해서 사용해주세요~
이건 각자+서로 할 일을 잘 keep up하기 위한 용도이지 귀찮은 일을 만들어서 괴롭히기 위한 용도가 아니니까!!! 유남쌩~
@GooJinSun @koyrkr @curious-curie

**Comment by GooJinSun** [comment]
@ssm0318 
이번 스프린트 기대가 됩니당!! 스장님 정리 감사합니다~~
몇가지 질문 + 제안 사항이 있어 코멘트 남겨봅니다!!

1. 데일리 개발 coverage report 적기
매일 coverage report 남기고 공유하는 거 서로 하는 일이나 어려움이 쉽게 공유될 수 있을 것 같아서 좋아요!
지금 올려주신 템플릿은 각자 레포트가 다른 이슈에 정리가 되어있는데
전체적인 진행 상황이나 각자의 progress를 한눈에 볼 수 있도록
![image](https://user-images.githubusercontent.com/37523788/99184187-87a78080-2784-11eb-8b7a-118efe66bc00.png)
이런 summary표는 하나 이슈에 정리해두면 어떨까하는 의견을 내봅니다~
각자 기록을 남기면 스스로 기록하고 자극을 받을 수 있고, 다른 사람들 개발 속도에 신경쓰지 않고 자신의 페이스대로 갈 수 있다는 장점이 있을 것 같긴 하지만요! 다들 어떻게 생각하시는지 궁금합니다! @ssm0318 @curious-curie @koyrkr 

2. <지나와 함께하는 왁자지껄 코딩 타임> 참석하기, 3. 효율적으로 + 명확하게 소통하기, 4. 냄새 안 나는 코딩하기
다 너무 좋아요!

5. 팀원 챙기기

**Comment by ssm0318** [comment]
@GooJinSun 
1. 저는 네 개 이어붙이면 스크롤하는게 귀찮을까봐 + 각자 피드에 가서 댓글 달아주기가 애매해질 것 같아서 그렇게 했는데 제 귀차니즘 역치는 남들과 다를 수 있다는건 인정합니다!! 다른 분들 의견에 따를게요!
2. 읽어주셔서 감사합니다!
3. 안 됩니다! 찐따 엔요 특히 안 돼요!!!!!

**Comment by GooJinSun** [comment]
1. 아 데일리 레포트를 싹다 네명꺼를 이어붙이자는 거는 아니었구 그냥 각자의 progress를 보는 정도를 의미한거였오!!

**Comment by ssm0318** [comment]
회의록 모음 [https://docs.google.com/document/d/1c6vBW-hcshKDnD4PIufj40exN7BMFFzQENCmTOiD6RY/edit](https://docs.google.com/document/d/1c6vBW-hcshKDnD4PIufj40exN7BMFFzQENCmTOiD6RY/edit)
