### ISSUE TITLE
[Sprint 5] To-do

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#59]
_Last Updated:_ Nov. 17th, 2020

무엇이 남았을까요~
sprint 5때도 건강하려면 sprint4때 어디까지 해야할까요~

- (프사, 아이콘) <-- 안 해도 됨
- 테스트 90% 이상
- deploy
- pg
- locust
- caching
- 포스터
- 발표 준비
- debugging
- refactoring
- 영상
- 서비스 핵심 컨셉 정리
-------
- 모바일 대응

**Comment by koyrkr** [comment]
### 질문
- pg는 무엇인가요?

### 의견
- Sprint 4때 최대한 테스트를 그때그때 90%에 가깝게 해두는게 좋을 것 같아요! 같은 맥락에서 debugging도 함께...?

**Comment by ssm0318** [comment]
@koyrkr [이것](https://www.postgresql.org/) 입니다 ㅎㅎ
의견 감사합니다~~~ 이따 회의 때 더 얘기해보아용 ~_~

**Comment by ssm0318** [comment]
static files
