### ISSUE TITLE
[Sprint 4] Week2 To-dos

### ISSUE THREAD

**Issue by ssm0318** [swsnu/swpp2020-team8#71]
일
- [ ] Csrf token testing - @GooJinSun 
- [x] Response Request (view, testing, unique together) - @GooJinSun 
- [x] Noti API 수정 + 테스팅 + 읽음처리  - @curious-curie 
- [x] Friendship View  + 테스팅 - @koyrkr 
- [ ] Friend Request View + 테스팅 - @koyrkr 
- [x] Permission 추가 처리 - @ssm0318 
- [x] Like unique constrainst - @ssm0318 
- [x] Feed, comment, account 테스팅 - @ssm0318 

월
- [ ] Noti Response Request - @GooJinSun 
- [ ] Post Edit page (api, testing, page markup) - @GooJinSun 
- [x] Question detail (View anonymous) - @GooJinSun 
- [ ] Question Send Call - @GooJinSun 
- [x] Comment Delete Call - @curious-curie  
- [x] CommentItem에서 비밀 댓글 안보여주기 - @curious-curie 
- [x] Private 댓글의 reply는 무조건 private - @curious-curie 
- [x] PostItem  Author 익명화 업데이트 - @curious-curie  
- [ ] FriendRequest, Response Request => Noti Create - @koyrkr 
- [x] Friendship View  + 테스팅 - @koyrkr 
- [ ] FriendRequest View + 테스팅 - @koyrkr 
- [x] 친구 관련 Permission 추가 처리 - @ssm0318 
- [x] Feed, comment 추가 테스팅 - @ssm0318 

화
- [ ] 볼 수 없는 게시글인 경우 팝업 or 경고 메시지 후 경고 페이지 403 Redirect - @GooJinSun 
- [ ] User Page에서 친구 아닌 경우 게시글 대신 경고 메시지 - @GooJinSun 
- [ ] 친구가 없는 유저가 친구 피드에 들어갔을 때 ‘친구 맺어보세요' 문구 - @GooJinSun 
- [ ] Notification Page (api linking-read, testing) - @GooJinSun 
- [ ] Friend List API - @curious-curie 
- [ ] Friend Delete - @curious-curie 
- [x] Post Delete API, Action - @curious-curie 
- [x] Share_with_friends / share_anonymously 하나 이상 체크 - @koyrkr 
- [ ] Like / Unlike Call - Post, Comment - @koyrkr 
- [ ] User Page - @ssm0318 
- [ ] Friend Search - @ssm0318 
- [ ] 사람 검색 결과 리스트에서 친구 요청, 친구 끊기 - @ssm0318 
- [ ] comment, post related fe testing 

수~
- [ ] 모바일 대응 - @GooJinSun 
- [x] 머신러닝 - @ssm0318 
- [ ] 무한스크롤 - @curious-curie  
- [ ] Question Selection min-select limit - @curious-curie

**Comment by ssm0318** [comment]
전체 progress 확인할 수 있도록 각자 daily to do coverage 이외에 여기도 체크 부탁해용
(저번에 올렸던 to-do list는 닫았습니다 참고로)

**Comment by GooJinSun** [comment]
화
- [x] SonarCloud 이슈 남기기 (화~) - @koyrkr
- [ ] SonarCloud 배지 이슈 해결 (금) - @koyrkr
- [ ] FriendRequest View + 테스팅 - @koyrkr 
- [ ] Like / Unlike Call - Post - @koyrkr
- [ ] Login Page WarningMessage - @koyrkr 
- [ ] 레포트 - @koyrkr 
- [ ] deploy (sprint 5부터) - 진선 프론트, 지나 백

- [x] response request 수정 - @GooJinSun
- [ ] Post Edit page (api, testing, page markup) - @GooJinSun 
- [ ] Question Send Modal api linking - @GooJinSun 
- [ ] Notification Page (api linking-read, testing) - @GooJinSun
- [ ] 테스트 90% 이상- @curious-curie, @GooJinSun
- `frontend/src/module/question.test.js`
- [ ] 볼 수 없는 게시글인 경우 팝업 or 경고 메시지 후 경고 페이지 403 Redirect - @GooJinSun 
- [ ] User Page에서 친구 아닌 경우 게시글 대신 경고 메시지 - @GooJinSun
- [ ] 친구가 없는 유저가 친구 피드에 들어갔을 때 ‘친구 맺어보세요' 문구 - @GooJinSun
- [ ] deploy (sprint 5부터) - 진선 프론트, 지나 백

- [ ] FriendRequest, Response Request => Noti Create - @curious-curie (규리야 고마워) 
- [ ] Noti Response Request -  - @curious-curie (규리야 고마워)  
- [ ] Friend List API - @curious-curie
- [ ] Friend Delete - @curious-curie
- [ ] comment, post related fe testing - @curious-curie, @GooJinSun
- [ ] 무한스크롤 - @curious-curie  
- [ ] Question Selection min-select limit - @curious-curie 

- [ ] User Page - @ssm0318 
- [ ] Friend Search - @ssm0318 
- [ ] 사람 검색 결과 리스트에서 친구 요청, 친구 끊기 - @ssm0318 

- [ ] locust(일) - @ssm0318 
- [ ] caching(일) - @curious-curie
- [ ] 모바일 대응 - @GooJinSun
